# Day 9 - Numpy

In [2]:
import numpy as np

### 1. The following array is given:
```
A = np.array([[4, 2, 1],
              [6, 4, 2]])
```
Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).

In response, print array to the console.

Tip: Use the np.expand_dims() function.

In [3]:
A = np.array([[4, 2, 1], [6, 4, 2]])
B = np.expand_dims(A, axis=0)
print(B)

[[[4 2 1]
  [6 4 2]]]


---

### 2. Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42. In response, print array to the console.

In [6]:
np.random.seed(42)
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image

array([[[102, 220, 225],
        [ 95, 179,  61],
        [234, 203,  92],
        ...,
        [ 41,  27,  87],
        [102, 225,  65],
        [170,   0, 238]],

       [[169, 170, 213],
        [159,  44, 250],
        [224, 206,  61],
        ...,
        [162, 118,  77],
        [228,  67,  21],
        [ 68,  30,  64]],

       [[237,  26, 118],
        [ 62, 157, 198],
        [  1, 151,  37],
        ...,
        [218, 189,  51],
        [193, 250, 243],
        [235,  34, 180]],

       ...,

       [[116, 102, 228],
        [ 29,  75,  71],
        [156, 133,  53],
        ...,
        [ 93,  45,  68],
        [124, 238,  76],
        [184, 185, 202]],

       [[216, 202, 116],
        [146, 168, 132],
        [236,  80,  45],
        ...,
        [169, 145, 212],
        [123,  50,  70],
        [ 11,  43,  62]],

       [[ 32,  52,  65],
        [155,   2,  86],
        [ 83, 240,  27],
        ...,
        [ 30,  57, 175],
        [ 72,  83, 171],
        [ 40, 114, 195]]

---

### 3. The following array is given:
```
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
```
Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

Tip: Use the np.expand_dims() function.

In [7]:
image_extended = np.expand_dims(image, axis=0)
print(image_extended)

[[[[102 220 225]
   [ 95 179  61]
   [234 203  92]
   ...
   [ 41  27  87]
   [102 225  65]
   [170   0 238]]

  [[169 170 213]
   [159  44 250]
   [224 206  61]
   ...
   [162 118  77]
   [228  67  21]
   [ 68  30  64]]

  [[237  26 118]
   [ 62 157 198]
   [  1 151  37]
   ...
   [218 189  51]
   [193 250 243]
   [235  34 180]]

  ...

  [[116 102 228]
   [ 29  75  71]
   [156 133  53]
   ...
   [ 93  45  68]
   [124 238  76]
   [184 185 202]]

  [[216 202 116]
   [146 168 132]
   [236  80  45]
   ...
   [169 145 212]
   [123  50  70]
   [ 11  43  62]]

  [[ 32  52  65]
   [155   2  86]
   [ 83 240  27]
   ...
   [ 30  57 175]
   [ 72  83 171]
   [ 40 114 195]]]]


---

### 4. Two randomly generated arrays are given:
```
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
```
Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).

In [13]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

# Start your code here
image1_expanded = np.expand_dims(image1, axis=0)
image2_expanded = np.expand_dims(image2, axis=0)
images = np.concatenate((image1_expanded, image2_expanded), axis=0)
print(images)
print(images.shape)

[[[[153  79 138]
   [129  73 182]
   [177 104  61]
   ...
   [169  21 124]
   [217  60 233]
   [ 80 233 226]]

  [[145  57 212]
   [ 40 220 145]
   [110  22 158]
   ...
   [ 58  16 211]
   [207 143 235]
   [214 122 114]]

  [[111 139 111]
   [ 36  41 170]
   [ 24  82 174]
   ...
   [ 94 242  82]
   [ 27  85 115]
   [  7 168  51]]

  ...

  [[123 188 130]
   [208 192  92]
   [214  59  25]
   ...
   [198 228  87]
   [245   0  16]
   [111  65   3]]

  [[193  83 246]
   [ 78 226 138]
   [132 196 171]
   ...
   [200  61  85]
   [ 80 208 128]
   [151 111  16]]

  [[201 121 239]
   [244 126 158]
   [108 122 122]
   ...
   [176 159 229]
   [ 18 130 172]
   [255 164  75]]]


 [[[ 91 103 196]
   [ 87  31 234]
   [ 10  74 206]
   ...
   [ 84 209 235]
   [ 11   5 106]
   [111 211 230]]

  [[  9  24 155]
   [ 44 219  43]
   [211  40  52]
   ...
   [132 191  89]
   [190 147 226]
   [150 143 156]]

  [[ 53   1  78]
   [113  51  75]
   [157 122  50]
   ...
   [218 110 161]
   [170 242 198]
   [170 203

---

### 5. The following array is given:
```
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
```
Shape of this array is (1, 2, 3). Remove the unnecessary first dimension and extract (2, 3) array and print it to the console as shown below.

Tip: Use the np.squeeze() function.

In [14]:
A = np.array([[[1, 2, 3], [6, 3, 2]]])
print(np.squeeze(A))

[[1 2 3]
 [6 3 2]]


## Congratulate, Day 9 Finished!