# Day 5 - Numpy

In [2]:
import numpy as np

### 1. Using Numpy create the following array:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.

In [6]:
arr = np.arange(12).reshape(3, 4)
np.save('array.npy', arr)

array = np.load('array.npy')
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


---

### 2. Using Numpy create the following array:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.

In [7]:
arr = np.arange(12).reshape(-1, 4)
np.savetxt('array.txt', arr)

array = np.loadtxt('array.txt')
print(array)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


---

### 3. Using Numpy create and convert the following array into the list:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

In response, print list to the console.

In [8]:
arr = np.arange(12).reshape(-1, 4)

a = arr.tolist()
print(a)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


---

### 4. The following array is given:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Using the slice operator, transform this array into the following:

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```

In response, print transformed array to the console.

In [9]:
arr = np.arange(12).reshape(3, 4)
print(arr[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


---

### 5. The following array:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```

transform to this array:

```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

In response, print transformed array to the console.

In [16]:
arr = np.ones((4, 4))
print(np.pad(arr, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Congratulate, Day 5 Finished!