# Day 13 - Numpy

In [2]:
import numpy as np

### 1. The following arrays are given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Calculate arithmetic means of these arrays (elementwise) and print result to the console.

In [5]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

# Start your code here
# Method 1
print((A+B)/2)

# Method 2
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


---

### 2. The following arrays are given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Multiply these arrays (elementwise) and print result to the console.

In [7]:
# Method 1
print(A*B)

# Method 2
print(np.multiply(A, B))

[[12 12 18 10]
 [30  9  2 30]]


---

### 3. The following array is given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Calculate the square root of each element of this array and print result to the console.

Tip: Use the np.sqrt() function.

In [8]:
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


---

### 4. The following arrays are given:
```
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
```
Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.

In response, print result to the console.

In [12]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

# Start your code here
# Method 1
print(np.allclose((np.sin(A) ** 2 + np.cos(A) ** 2), B))

# Method 2
print(np.allclose((np.power(np.sin(A), 2) + np.power(np.cos(A), 2)), B))

True


---

### 5. The following arrays are given:
```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Shapes of these arrays:
```
A - 3x2

B - 2x3
```
Perform matrix multiplication A x B and print result to the console.

Tip: Use the np.dot() function.

In [14]:
A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])

# Start your code here
# Method 1
print(np.dot(A, B))

# Method 2
print(A.dot(B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


## Congratulate, Day 13 Finished!