# Day 6 - Numpy

In [1]:
import numpy as np

### 1. The following array:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```

transform to the following:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

In response, print transformed array to the console.

Tip: Use the slice operator and assign the appropriate values.

In [13]:
a = np.zeros((6, 6), dtype='int')
a[::2, ::2] = 10
a[1::2, ::2] = 5
print(a)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


---

### 2. Combine the following arrays into one as shown below and print it to the console.
```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```
Tip: Use the np.append() function.

In [14]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2], [0, 5, 2, 6]])

C = np.append(A, B, axis=0)

print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


---

### 3. The following arrays are given:
```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```
Extract the same elements (intersection) of the arrays as a list and print result to the console.

Tip: Use the np.intersect1d() function.

In [15]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3], [2, 8, 0, 9]])

C = np.intersect1d(A, B)
print(C)

[0 2 3]


---

### 4. The following array is given:
```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```
Extract all unique values of this array as a list and print it to the console.

Tip: Use the np.unique() function.

In [16]:
# First Method
A = np.array([[5, 1, 2, 1, 2], [9, 1, 9, 7, 5], [4, 1, 5, 7, 9]])
print(np.unique(A))

# Second Method
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(np.unique(A))

[1 2 4 5 7 9]
[1 2 4 5 7 9]


---

### 5. The following array is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```

Return a list of indexes with maximum values for each row from this array and print it to the console.

Tip: Use the np.argmax() function.

In [17]:
A = np.array([[0.4, 0.3, 0.3], [0.1, 0.1, 0.8], [0.2, 0.5, 0.3]])
print(np.argmax(A, axis=1))

[0 2 1]


## Congratulate, Day 6 Finished!