# Day 4 - Numpy

In [1]:
import numpy as np

### 1. Using Numpy create a two-dimensional array with the shape (10, 4) pseudo-randomly generated values from the normal distribution N(100, 5). Set the random seed to 30.

In [11]:
np.random.seed(30)
sigma = np.sqrt(5)
mu = 100
print(sigma * np.random.randn(10, 4) + mu)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]


---

### 2. The following array is given:

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

Iterate through this array and print each element to the console.

In [12]:
A = np.array([[1, 4, 3], [5, 2, 6]])
for i in np.nditer(A):
    print(i)

1
4
3
5
2
6


---

### 3. Using Numpy create a one-dimensional array (vector) consisting of eleven equally distributed numbers from the [0,1] interval.

In [13]:
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


---

### 4. Using Numpy create a one-dimensional array (vector) containing the possible result from the Big Lotto game. Set the random seed to 42. Print result to the console.
Tip: The result of this game is a 6-element vector of values from 1 to 49 inclusive.

In [14]:
np.random.seed(42)
print(np.random.choice(range(1, 50), size=6, replace=False))

[14 46 48 45 18 28]


---

### 5. Using Numpy create the following two-dimensional array:

```
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
```

Print result to the console as shown below.

In [15]:
print(np.diag([0, 1, 2, 3, 4, 5]))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


## Congratulate, Day 4 Finished!