# Day 7 - Numpy

In [2]:
import numpy as np

### 1. The following array is given:
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

Sort this array:

by row (ascending)

by column (ascending)

And print result to the console as shown below.

Tip: Use the np.sort() function.

In [3]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])

# Column wise sorting occurs
B = np.sort(A, axis=0)
print(B)

# Row wise sorting occurs (axis=1, by default)
C = np.sort(A, axis=1)
print(C)

[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]
[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]


---

### 2. Extract all elements from the following array with a value greater than 8 and print result to the console.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [6]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])
B = np.array(A[A > 8])
print(B)

[ 9.99  9.99 14.99]


---

### 3. The following array is given:
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.

Tip: Use the np.where() function.

In [8]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 14.99], [14.99, 2.39, 7.29]])
A[np.where(A > 10)] = 10.0
print(A)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


---

### 4. Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

Tip: Use the np.ravel() function.

In [10]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 14.99], [14.99, 2.39, 7.29]])
B = np.ravel(A)
print(B)

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


---

### 5. The following array is given:
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.

Tip: Use the np.zeros_like() function.

In [11]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 14.99], [14.99, 2.39, 7.29]])

B = np.zeros_like(A)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Congratulate, Day 7 Finished!