# Day 12 - Numpy

In [1]:
import numpy as np

### 1. The following array is given below:
```
A = np.random.randn(10, 4)
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```
Set the Numpy option to print arrays with specified precision. Set precision to 4 and print this array.

In [2]:
np.random.seed(42)
A = np.random.randn(10, 4)

# Start your code here
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


---

### 2. The following array is given:
```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation and print this array to the console.

In [5]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(suppress=True, precision=8)
print(A)

[0.0000012  0.00000017]


---

### 3. The following array is given:
```
A = np.random.randn(8, 4)
```
Remove the third column and print this array to the console.

Tip: Use the np.delete() function.

In [7]:
A = np.random.randn(8, 4)

np.delete(A, [3], axis=1)

array([[-0.03582604,  1.56464366, -2.6197451 ],
       [ 0.08704707, -0.29900735,  0.09176078],
       [-0.21967189,  0.35711257,  1.47789404],
       [-0.8084936 , -0.50175704,  0.91540212],
       [-0.5297602 ,  0.51326743,  0.09707755],
       [-0.70205309, -0.32766215, -0.39210815],
       [ 0.29612028,  0.26105527,  0.00511346],
       [-1.41537074, -0.42064532, -0.34271452]])

---

### 4. A one-dimensional array v (vector) is given:
```
v = np.array([3, 4, -2])
```
Calculate the norm of this vector and print result to the console.

In [8]:
v = np.array([3, 4, -2])

print(np.linalg.norm(v))

5.385164807134504


---

### 5. The following array is given:
```
A = np.random.randint(10, size=(100, 30))
```
Set the Numpy option to print only ten edge elements and then print this array to the console.

In [9]:
np.random.seed(42)
A = np.random.randint(10, size=(100, 30))

# Start your code here
np.set_printoptions(edgeitems=10)
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]


## Congratulate, Day 12 Finished!