# Day 2 - Numpy

In [1]:
import numpy as np

### 1. Check if the following arrays are equal (element-wise)

In [2]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

# <---- Write your code here ---->

print(np.allclose(A, B))

True


---

### 2. Check if the following arrays are equal (element-wise)

In [3]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

# <---- Write your code here ---->

# Method 1
print(A == B)

# Method 2
print(np.equal(A, B))

[False False  True]
[False False  True]


---

### 3. Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.

In [4]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

# <---- Write your code here ---->

# Method 1
print(A > B)

# Method 2
print(np.greater(A, B))

[ True False False False]
[ True False False False]


---

### 4. Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.

In [5]:
print(np.zeros((4, 4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


---

### 5. Using Numpy, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.

In [7]:
# Method 1
print(np.full(shape=(10, 10), fill_value=255, dtype=float))

print('\n')

# Method 2
print(np.ones(shape=(10, 10), dtype='float') * 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 2

## Congratulate, Day 2 Finished!