# Day 8 - Numpy

In [1]:
import numpy as np

### 1. The following array is given:
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.

Tip: Use the np.full_like() function.

In [2]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 14.99], [14.99, 2.39, 7.29]])

B = np.full_like(A, 9.99, dtype=float)
B

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

---

### 2. Using Numpy create a two-dimensional array (lower triangular matrix):

```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```

In response, print result to the console.

Tip: Use the np.tri() function.

In [4]:
print(np.tri(5, 5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


---

### 3. Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

Example:
```
[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]
 
 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]
```

In [6]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
               [[7, 2, 3, 1],
                [6, 2, 0, 9],
                [0, 1, 9, 1]]])
A

array([[[4, 5, 4, 2],
        [6, 3, 5, 1],
        [5, 2, 1, 2]],

       [[7, 2, 3, 1],
        [6, 2, 0, 9],
        [0, 1, 9, 1]]])

---

### 4. Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [10]:
image = np.random.randint(low=0, high=255, size=(200, 300), dtype=np.uint8)
print(image)

[[252   4   3 ... 236 177 182]
 [ 23 216   0 ... 148  81 193]
 [129 241 231 ... 171  11  64]
 ...
 [152 172  12 ... 102  22  48]
 [135 224 133 ...  35 210 179]
 [ 12  35 136 ...  18 128 179]]


---

### 5. The following array is given:
```
image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
```
Sort this array along the rows in ascending order and assign to the variable image_sorted.

In [13]:
image = np.random.randint(low=0, high=255, size=(200, 300), dtype=np.uint8)
image_sorted = np.sort(image, axis=1)
print(image_sorted)

[[  0   2   3 ... 253 254 254]
 [  0   1   3 ... 254 254 254]
 [  1   2   2 ... 254 254 254]
 ...
 [  0   0   1 ... 251 253 254]
 [  0   0   0 ... 248 249 253]
 [  2   4   4 ... 253 253 253]]


## Congratulate, Day 8 Finished!