# Day 10 - Numpy

In [1]:
import numpy as np

### 1. The following array is given:
```
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
```
Shape of this array is (4, 1). Remove the unnecessary dimension and extract (4, ) array and print result to the console.

Tip: Use the np.squeeze() function.

In [2]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])
print(np.squeeze(A).shape)

(4,)


---

### 2. The following array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Using the slice operator, transform this array into the following:
```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```
In response, print transformed array to the console.

In [3]:
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(B[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


---

### 3. The following  array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Using the slice operator, transform this array into the following:
```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```
In response, print transformed array to the console.

In [4]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


---

### 4. Random seed is set to 42. The following array is given:
```
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
```
Extract the first channel (index 0) of this image array and print it to the console.

In [5]:
np.random.seed(42)
image = np.random.randint(low=0, high=255, size=(10, 10, 3), dtype=np.uint8)

# Start your code here
print(image[:, :, 0])

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35  11 201]
 [ 10 207  93 150   0 189  23   1 139  50]
 [ 51 233 222 243 251 168 197 130  11  37]
 [ 15 134 174 167 235 166  16 101  41  88]
 [241  51 168 241 206 170  43  89   4   1]]


---

### 5. The following array is given:
```
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
```
Extract any array of shape (5, 5, 3) from this array and assign to the result variable.

In [6]:
result = image[:5, :5, :]
print(result)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  [  3  98 243]
  [ 14 149 245]]

 [[203 152 102]
  [214 240  39]
  [121  24  34]
  [114 210  65]
  [239  39 214]]

 [[116 237 109]
  [ 85  99 172]
  [226 153 103]
  [235 146  36]
  [151  62  68]]

 [[ 76 248  87]
  [233 212 184]
  [235 245  26]
  [213 157 253]
  [ 68 240  37]]

 [[ 20 153 243]
  [ 46 160  68]
  [ 19 158 203]
  [209 226  77]
  [ 57  77 149]]]


## Congratulate, Day 10 Finished!