# Day 11 - Numpy

In [1]:
import numpy as np

### 1. The following arrays are given:
```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
Concatenate these arrays as follows:
```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
In response, print this array to the console.

Tip: Use the np.concatenate() function.

In [2]:
A = np.array([[3, 4, 5], [8, 3, 1]])
B = np.array([[0, 5, 2], [4, 2, 1]])

# Start your code here
print(np.concatenate([A, B]))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


---

### 2. The following arrays are given:
```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```
Concatenate these arrays into one as shown below:
```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```
In response, print this array to the console.

In [3]:
data = np.array([[4.3, 4.2], [3.1, 3.6]])
target = np.array([[0], [1]])

# Start your code here
print(np.concatenate([data, target], axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


---

### 3. The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one array as shown below. In response, print this array to the console.

Tip: Use the np.column_stack() function.

In [4]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

# Start your code here
print(np.column_stack([feature1, feature2, feature3]))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


---

### 4. The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split this array into three parts:

the first two columns assign to the A1 variable

the next four columns assign to the A2 variable

the last two columns assign to the A3 variable

In response, print these arrays to the console as shown below.

Tip: Use the function np.split().

In [12]:
np.random.seed(42)
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

# Start your code here
# Method 1
A1 = np.split(A, [2, 6, 8], axis=1)[0]
print(A1)

A2 = np.split(A, [2, 6, 8], axis=1)[1]
print(A2)

A3 = np.split(A, [2, 6, 8], axis=1)[2]
print(A3)

# Method 2
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


---

### 5. The following array is given:
```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Calculate the total number of non-zero elements in this array and print it to the console.

Tip: Use the np.count_nonzero() function.

In [13]:
np.random.seed(42)
A = np.random.randint(low=0, high=2, size=(10, 6))

# Start your code here
print(np.count_nonzero(A))

31


## Congratulate, Day 11 Finished!