# Day 20 - Numpy

In [1]:
import numpy as np

### 1. Calculate the average value for each column. Round the result to two decimal places and print it to the console.

In [2]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])

# Start your code here
print(np.round(np.mean(playway_values, axis=0), 2))

[  283.14   295.25   268.69   282.3  48688.05]


---

### 2. Calculate the new column: the difference between the highest and lowest price.

Steps:
- Assign the calculated difference to the max_min_diff variable
- Add the calculated column (variable max_min_diff) to the array playway_values at the end.

In response, print result to the console.

In [3]:
np.set_printoptions(suppress=True)
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

---

### 3. Extract rows from this array where closing price (column with index 3) is greater than 300.0. In response, print result to the console.

In [4]:
print(playway_values[playway_values[:, 3] > 300.0])

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


---

### 4. From this array extract the first 10 rows with the highest volume sorted in descending order.

In [5]:
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


---

### 5. Add to this array column that returns 1 in case the close price is higher than the open price, otherwise 0.

In [6]:
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

## Congratulate, Day 20 Finished!