# Day 16 - Numpy

In [1]:
import numpy as np

### 1. The following polynomials are given:
```
W(x) = 4x^2 + 5x + 1
Q(x) = 2x^3 + 4x^2 - 5x + 1
```


Perform the following operations and print results to the console as shown be
```
W(x) + Q(x)
W(x) - Q(x)
W(x) * Q(x)
W(x) + 2Q(x)
```

In [3]:
W = [4, 5, 1]
Q = [2, 4, -5, 1]

print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, np.polymul(2, Q)))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


---

### 2. The following array is given:
```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, ```]])
```
Use the sign function for thisrray.

Reminder: The sign function works as follows: returns -1 for negative values, zero for zero, and 1 for posite values.

Tip: Use the np.sign() function.

In [4]:
A = np.array([[-4, 3, 0, 1, -5], [6, -4, -2, 1, 3]])

print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


---

### 3. Using the np.arange() function, generate the following array:
```
['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']
```
In response print this array to the console.

In [6]:
print(np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]'))

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


---

### 4. Using the np.arange() function, generate the following array:
```
[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]
```
In response, print this array to the console.

In [9]:
print(np.arange('2021-01', '2022-01', dtype='datetime64[M]').reshape(-1, 3))

[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]


---

### 5. Using the np.datetime64() function, generate today's date and print result to the console.

In [11]:
print(np.datetime64('today'))

2023-11-12


## Congratulate, Day 16 Finished!