# Day 14 - Numpy

In [1]:
import numpy as np

### 1. The following array (square matrix) is given:
```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Calculate the determinant of this matrix and print it to the console.

Tip: Use the np.linalg.det() function.

In [2]:
A = np.array([[-2, 0, 4], [5, 2, -1], [-4, 2, 4]])

# Start your code here
print(np.linalg.det(A))

51.999999999999986


---

### 2. The following array (square matrix) is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Calculate eigenvalues and their corresponding eigenvectors of this matrix and print to the console as shown below.

Tip: Use the np.linalg.eig() function.

In [4]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])

# Start your code here
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


---

### 3. The following array (square matrix) is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the inverse matrix to this matrix and print it to the console.

Tip: Use the np.linalg.inv() function.

In [5]:
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


---

### 4. The following array (square matrix) is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the trace of this matrix (sum of elements on the main diagonal) and print result to the console.

Tip: Use the np.trace() function.

In [6]:
print(np.trace(A))

-5


---

### 5. The following arrays are given:
```
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
```
Shapes of these arrays:
```
A - 4x2

B - 1x8
```
Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.

In [9]:
A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

# Start your code here
B = B.reshape(A.shape[1], A.shape[0])
print(A.dot(B))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


## Congratulate, Day 14 Finished!